version: '3'
services:
  python-app:
    build:
      context: apps/python
    volumes:
      - ./apps/python:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-check"]
      interval: 3s
      timeout: 60s
      retries: 20
  test:
    build:
      context: test
    environment:
      TARGET_HOST: "http://python-app:8080"
    volumes:
      - ./test:/app/
    depends_on:
      python-app:
        condition: service_healthy

